# Test goal: build with hipSYCL (ROCm backend) to check SYCL code compatibility
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   Compiler: Clang
#   GPU: hipSYCL
#   Scope: configure, build
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Build type: RelWithAssert
#   Compiler: Clang 15
#   MPI: CUDA-aware MPICH (NVIDIA build); threadMPI (AMD build)
#   SIMD: AVX2_256

gromacs:hipsycl-rocm:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
    - .use-sycl
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-15-cuda-11.7.1-hipsycl-0.9.4-rocm-5.3.3
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX2_256"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    CMAKE_GPU_OPTIONS: "-DGMX_GPU=SYCL -DGMX_SYCL=ACPP -DHIPSYCL_TARGETS=hip:gfx906,gfx1034 -DGMX_GPU_FFT_LIBRARY=vkFFT"
    # Unset COMPILER_LAUNCHER (previously set to ccache) because it conflicts with hipSYCL's syclcc-launcher
    CMAKE_EXTRA_OPTIONS: "-DCMAKE_C_COMPILER_LAUNCHER= -DCMAKE_CXX_COMPILER_LAUNCHER= -DGMX_INSTALL_LEGACY_API=ON"
    COMPILER_MAJOR_VERSION: 15

gromacs:hipsycl-rocm:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .before_script:default
    # Not using ccache because it plays poorly with syclcc-launcher
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-15-cuda-11.7.1-hipsycl-0.9.4-rocm-5.3.3
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-rocm:configure

gromacs:hipsycl-rocm:test:
  extends:
    - .variables:default
    - .gromacs:base:test
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-15-cuda-11.7.1-hipsycl-0.9.4-rocm-5.3.3
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "amd.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 1
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-rocm:build

gromacs:hipsycl-rocm:regressiontest:
  extends:
    - .variables:default
    - .gromacs:base:regressiontest
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-15-cuda-11.7.1-hipsycl-0.9.4-rocm-5.3.3
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 1
    REGRESSIONTEST_OMP_RANK_NUMBER: 2
    KUBERNETES_EXTENDED_RESOURCE_NAME: "amd.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 1
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-rocm:build
    - job: regressiontests:prepare


gromacs:hipsycl-nvidia-mpi:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
    - .use-sycl
    - .use-mpi
    - .rules:weekly-not-for-release
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-15-cuda-11.7.1-hipsycl-0.9.4-rocm-5.3.3
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX2_256"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    CMAKE_GPU_OPTIONS: "-DGMX_GPU=SYCL -DGMX_SYCL=ACPP -DHIPSYCL_TARGETS='cuda:sm_50,sm_52,sm_60,sm_61,sm_70,sm_75' -DGMX_GPU_FFT_LIBRARY=VkFFT"
    # Unset COMPILER_LAUNCHER (previously set to ccache) because it conflicts with hipSYCL's syclcc-launcher
    CMAKE_EXTRA_OPTIONS: "-DCMAKE_C_COMPILER_LAUNCHER= -DCMAKE_CXX_COMPILER_LAUNCHER="
    COMPILER_MAJOR_VERSION: 15

gromacs:hipsycl-nvidia-mpi:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .before_script:default
    # Not using ccache because it plays poorly with syclcc-launcher
    - .rules:weekly-not-for-release
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-15-cuda-11.7.1-hipsycl-0.9.4-rocm-5.3.3
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-nvidia-mpi:configure

gromacs:hipsycl-nvidia-mpi:test-gpucommupd-MPI:
  extends:
    - .gromacs:base:test
    - .rules:weekly-not-for-release
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-15-cuda-11.7.1-hipsycl-0.9.4-rocm-5.3.3
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
    GMX_ENABLE_DIRECT_GPU_COMM: 1
    GMX_FORCE_GPU_AWARE_MPI: 1
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-nvidia-mpi:build

gromacs:hipsycl-nvidia-mpi:regressiontest-gpucommupd-MPI:
  # Test parallelism np/ntomp: 2/2
  # Test parallelism GPU: direct communications, update
  extends:
    - .gromacs:base:regressiontest
    - .rules:weekly-not-for-release
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-15-cuda-11.7.1-hipsycl-0.9.4-rocm-5.3.3
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 2
    REGRESSIONTEST_PARALLEL: "-np"
    GMX_ENABLE_DIRECT_GPU_COMM: 1
    GMX_FORCE_GPU_AWARE_MPI: 1
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-nvidia-mpi:build
    - job: regressiontests:prepare
  artifacts:
    paths:
      - regressiontests
    when: always
    expire_in: 1 week

